version: '3.8'

networks:
  monitoring: 
    driver: bridge

services:
  nestjs-metrics:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3002:3002
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    ports:
      - 9090:9090