version: '3.8'

networks:
  monitoring: 
    driver: bridge
    
volumes:
  grafana_data: {}

services:
  nestjs-metrics:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3002:3002
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    ports:
      - 9090:9090